import type { Quest } from '../domain/quest/types';

export const quests: Quest[] = [
  {
    id: 'promise-basics',
    chapterId: 'javascript-basics',
    title: 'Promise 到底解决了什么问题？',
    description: '先击败第一只小怪：理解 Promise 存在的核心价值。',
    difficulty: 1,
    prerequisiteQuestIds: [],
    reward: { xp: 50 },
    hints: [
      'Promise 描述的是一个未来才会得到结果的异步操作。',
      '它并不会让 JavaScript 变成多线程，而是让异步结果的成功、失败和等待状态更容易被组织。',
    ],
    knowledgeNodeIds: ['promise'],
    skillDimensions: ['recall', 'understand'],
    type: 'understand',
    challenge: {
      type: 'choice',
      question: '在 JavaScript 中，Promise 最核心的作用是什么？',
      options: [
        { id: 'A', label: '让 JavaScript 代码变成多线程' },
        { id: 'B', label: '管理异步操作的状态与结果' },
        { id: 'C', label: '让所有函数自动变成异步函数' },
        { id: 'D', label: '提高 JavaScript 的 CPU 执行速度' },
      ],
      correctAnswer: 'B',
    },
  },
  {
    id: 'promise-state',
    chapterId: 'javascript-basics',
    title: 'Promise 的三种状态',
    description: '理解 pending、fulfilled、rejected 以及状态只能单向变化的规则。',
    difficulty: 1,
    prerequisiteQuestIds: ['promise-basics'],
    reward: { xp: 60 },
    hints: [
      'Promise 初始处于 pending，之后只能进入 fulfilled 或 rejected。',
      'Promise 一旦 settled，就不会再次改变状态。',
    ],
    knowledgeNodeIds: ['promise-state'],
    skillDimensions: ['recall', 'understand'],
    type: 'understand',
    challenge: {
      type: 'choice',
      question: 'Promise 的状态变化中，哪一种描述正确？',
      options: [
        { id: 'A', label: 'pending → fulfilled / rejected，settled 后不能再次改变' },
        { id: 'B', label: 'fulfilled → pending → rejected' },
        { id: 'C', label: 'rejected 可以重新变成 pending' },
        { id: 'D', label: 'Promise 可以同时处于 fulfilled 和 rejected' },
      ],
      correctAnswer: 'A',
    },
  },
  {
    id: 'promise-chain',
    chapterId: 'javascript-basics',
    title: 'Promise 链式调用',
    description: '观察同步日志与微任务的执行顺序，击败第二只小怪。',
    difficulty: 2,
    prerequisiteQuestIds: ['promise-state'],
    reward: { xp: 80 },
    hints: [
      '先执行当前同步代码，再处理 Promise.then 注册的微任务。',
      'console.log(3) 仍然属于当前同步任务，因此会在 then 回调之前执行。',
    ],
    knowledgeNodeIds: ['promise', 'microtask'],
    skillDimensions: ['understand', 'apply'],
    type: 'reason',
    challenge: {
      type: 'output',
      question: `执行下面代码，最终输出顺序是什么？\n\nconsole.log(1);\nPromise.resolve().then(() => console.log(2));\nconsole.log(3);`,
      options: [
        { id: 'A', label: '1 → 2 → 3' },
        { id: 'B', label: '1 → 3 → 2' },
        { id: 'C', label: '2 → 1 → 3' },
        { id: 'D', label: '3 → 1 → 2' },
      ],
      correctAnswer: 'B',
    },
  },
  {
    id: 'event-loop',
    chapterId: 'javascript-basics',
    title: 'Event Loop 执行顺序',
    description: '分析同步代码与 Microtask 的执行顺序，建立 Event Loop 的基本心智模型。',
    difficulty: 2,
    prerequisiteQuestIds: ['promise-chain'],
    reward: { xp: 90 },
    hints: [
      '当前同步代码执行完之后，Promise.then 回调会作为 Microtask 执行。',
      '先问自己：哪些代码属于当前同步执行，哪些代码被放到了后续队列。',
    ],
    knowledgeNodeIds: ['microtask', 'event-loop'],
    skillDimensions: ['apply', 'debug'],
    type: 'reason',
    challenge: {
      type: 'output',
      question: `执行下面代码，最终输出顺序是什么？\n\nconsole.log('A');\nPromise.resolve().then(() => console.log('B'));\nconsole.log('C');`,
      options: [
        { id: 'A', label: 'A → B → C' },
        { id: 'B', label: 'A → C → B' },
        { id: 'C', label: 'B → A → C' },
        { id: 'D', label: 'C → A → B' },
      ],
      correctAnswer: 'B',
    },
  },
  {
    id: 'async-await-final',
    chapterId: 'javascript-basics',
    title: 'async / await 最终试炼',
    description: '综合判断 async / await 与 Promise 的执行关系。',
    difficulty: 3,
    prerequisiteQuestIds: ['event-loop'],
    reward: { xp: 100 },
    hints: [
      'await 会暂停当前 async 函数的后续执行，但不会阻塞整个 JavaScript 主线程。',
      'await 后续代码会在 Promise settled 后以微任务的形式继续执行。',
    ],
    knowledgeNodeIds: ['promise', 'event-loop', 'async-await'],
    skillDimensions: ['apply', 'debug', 'transfer'],
    type: 'reason',
    challenge: {
      type: 'choice',
      question: `下面代码最终输出顺序是什么？\n\nasync function run() {\n  console.log('A');\n  await Promise.resolve();\n  console.log('B');\n}\nrun();\nconsole.log('C');`,
      options: [
        { id: 'A', label: 'A → B → C' },
        { id: 'B', label: 'B → A → C' },
        { id: 'C', label: 'A → C → B' },
        { id: 'D', label: 'C → A → B' },
      ],
      correctAnswer: 'C',
    },
  },
  {
    id: 'race-condition',
    chapterId: 'javascript-basics',
    title: 'Race Condition 调试',
    description: '定位多个异步操作完成顺序不确定导致的数据覆盖问题。',
    difficulty: 3,
    prerequisiteQuestIds: ['async-await-final'],
    reward: { xp: 120 },
    hints: [
      '发起顺序不代表完成顺序，先完成的异步操作可能覆盖后完成操作的数据。',
      '调试时先确认共享状态是谁写入的，以及写入发生的先后顺序。',
    ],
    knowledgeNodeIds: ['async-await', 'event-loop', 'race-condition'],
    skillDimensions: ['apply', 'debug', 'transfer'],
    type: 'debug',
    challenge: {
      type: 'choice',
      question: '两个异步请求同时更新同一个状态，后发请求反而先完成，最需要防范什么问题？',
      options: [
        { id: 'A', label: 'Race Condition 导致旧结果覆盖新结果' },
        { id: 'B', label: 'Promise 自动把两个请求合并' },
        { id: 'C', label: 'await 会让两个请求按发起顺序完成' },
        { id: 'D', label: 'Event Loop 会阻止第二个请求执行' },
      ],
      correctAnswer: 'A',
    },
  },
];

export const firstQuest = quests[0];
